name: Release ZIP

on:
  push:
    tags:
      - '*'

permissions:
  contents: write # Required for publishing releases.

jobs:
  release:
    name: Release ZIP
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Create plugin ZIP
        run: git archive --prefix=update-pilot/ --output="update-pilot.${{ github.ref_name }}.zip" HEAD

      - name: Publish a release with plugin ZIP
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "${{ github.ref_name }}" "update-pilot.${{ github.ref_name }}.zip"
